export const guestsList = [
    { id: 1, name: "The Nyamweya Family" },
    { id: 2, name: "James Kipchoge" },
    { id: 3, name: "Sarah Muthoni" },
    { id: 4, name: "David Kimani" },
    { id: 5, name: "The Ochieng Crew" },
    { id: 6, name: "Margaret Wanjiru" },
    { id: 7, name: "Peter Muema" },
    { id: 8, name: "The Kariuki Squad" },
    { id: 9, name: "Amina Hassan" },
    { id: 10, name: "Joseph Kiplagat" },
    { id: 11, name: "The Koech Brothers" },
    { id: 12, name: "Diana Omondi" },
    { id: 13, name: "Samuel Kipchoge" },
    { id: 14, name: "The Mutua Bunch" },
    { id: 15, name: "Hannah Kiplagat" },
    { id: 16, name: "Lucas Kariuki" },
    { id: 17, name: "The Ngugi Family" },
    { id: 18, name: "Sophia Kipchoge" },
    { id: 19, name: "Michael Ngetich" },
    { id: 20, name: "The Kiplagat Fam" },
    { id: 21, name: "Victoria Ochieng" },
    { id: 22, name: "Abraham Kiplagat" },
    { id: 23, name: "The Mwangi Crew" },
    { id: 24, name: "Natasha Kipchoge" },
    { id: 25, name: "Christopher Kariuki" }
];
